HCK-7033: remove properties that do not pass dependency check
hackolade/CosmosDB-with-Gremlin-API pull request #35
Opened 2024-08-12 09:41 UTC by AlikRakhmonov

2024-08-14 13:33 UTC, Vitalii4as requested changes

2024-08-14 13:33 UTC, Vitalii4as commented on properties_pane/entity_level/entityLevelConfig.json
> +				"preserveOnCleanDependencies": true,
Shouldn't we have the same for `parentCollections`

2024-08-19 09:29 UTC, Vitalii4as approved these changes

2024-08-19 11:24 UTC, VitaliiBedletskyi approved these changes

2024-08-19 16:02 UTC, merged